### ISSUE TITLE
Exception thrown in texture.h

### ISSUE THREAD

**Issue by AustinCarr** [lsempe/uipg#2]
When running sample the sample projects an exception is thrown: "Unhandled exception at 0x74C5C41F in sample.hud.exe: Microsoft C++ exception: std::exception at memory location 0x0028F184."

This occurs on __line 91 in texture.h__.

**Comment by Fiercy** [comment]
I think i have the same issue with texture

**Comment by lsempe** [comment]
Hi Fiercy,

I wasn't able to reproduce it before. I will look into it tonight.

Thanks!

-----Original Message-----

**Comment by Fiercy** [comment]
I fixed the issue for some reason the contents its looking for are not there (fonts,textures, etc...). So I just went to the content installer and manually grabbed and placed the folder. I did rub content installer app but maybe I did something wrong. 

But after I run the examples I have a question why is the menu example has one texture that I can't seem to even be able to interact with and why the cursor can't leave the boarders of the application when it's in the windowed mode. Thank you.

**Comment by lsempe** [comment]
I'm happy you found a workaround, I'll still look into it to make sure it doesn't happen to anyone else.

I'm not sure which texture you mean, I'll rub the demo when I get home and I'll let you know. 

As for the window borders, it's something I didn't implement in the sample framework. I'll add it to my list of things to do, I agree it would be nice to have that. Thanks!

-----Original Message-----

**Comment by lsempe** [comment]
I pushed a fix - the Win32 projects were not properly setup to run the post build event that makes sure the content files are placed in the proper folder.
